apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: openapi-demo-api-rlp
  namespace: openapi-demo
  annotations:
    argocd.argoproj.io/sync-wave: '33'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: openapi-demo-api
  limits:
    general-user:
      rates:
      - limit: 5
        window: 10s
      counters:
      - expression: auth.identity.userid
      when:
      - predicate: request.path != '/health'
      - predicate: auth.identity.userid != 'bob'
    bob-limit:
      rates:
      - limit: 2
        window: 10s
      counters:
      - expression: auth.identity.userid
      when:
      - predicate: request.path != '/health'
      - predicate: auth.identity.userid == 'bob'
