apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/00-kuadrant-namespace.yaml
  - resources/10-gatewayclass-openshift-default.yaml
  - resources/20-rhcl-operator.yaml
  - resources/30-kuadrant-cr.yaml

