apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel
  namespace: rhcl-observability
  annotations:
    argocd.argoproj.io/sync-wave: "40"
---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: rhcl-observability
  annotations:
    argocd.argoproj.io/sync-wave: "41"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  mode: deployment
  serviceAccount: otel
  config:
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}

    exporters:
      otlp/tempo:
        auth:
          authenticator: bearertokenauth
        endpoint: tempo-simplest-gateway.rhcl-observability.svc.cluster.local:8090
        headers:
          X-Scope-OrgID: dev
        tls:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
          insecure: false

    extensions:
      bearertokenauth:
        filename: /var/run/secrets/kubernetes.io/serviceaccount/token

    service:
      extensions:
        - bearertokenauth
      pipelines:
        traces:
          receivers:
            - otlp
          exporters:
            - otlp/tempo

