apiVersion: console.openshift.io/v1
kind: UIPlugin
metadata:
  name: distributed-tracing
  annotations:
    argocd.argoproj.io/sync-wave: "90"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  type: DistributedTracing

