apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel
  namespace: rhcl-observability
  annotations:
    argocd.argoproj.io/sync-wave: "40"
---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: rhcl-observability
  annotations:
    argocd.argoproj.io/sync-wave: "41"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  mode: deployment
  serviceAccount: otel
  config:
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}

    exporters:
      otlp/tempo:
        endpoint: tempo-simplest-distributor.rhcl-observability.svc.cluster.local:4317
        headers:
          X-Scope-OrgID: dev
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers:
            - otlp
          exporters:
            - otlp/tempo

