apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel
  namespace: rhcl-observability
  annotations:
    argocd.argoproj.io/sync-wave: "40"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rhcl-observability-otel-k8sattributes
  annotations:
    argocd.argoproj.io/sync-wave: "40"
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["replicasets", "deployments", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rhcl-observability-otel-k8sattributes
  annotations:
    argocd.argoproj.io/sync-wave: "40"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rhcl-observability-otel-k8sattributes
subjects:
  - kind: ServiceAccount
    name: otel
    namespace: rhcl-observability
---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: rhcl-observability
  annotations:
    argocd.argoproj.io/sync-wave: "41"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  mode: deployment
  serviceAccount: otel
  config:
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}

    processors:
      k8sattributes:
        auth_type: serviceAccount
        extract:
          metadata:
            - k8s.namespace.name
            - k8s.pod.name
            - k8s.deployment.name
            - k8s.node.name
        pod_association:
          - sources:
              - from: connection

    exporters:
      otlp/tempo:
        endpoint: tempo-simplest-distributor.rhcl-observability.svc.cluster.local:4317
        headers:
          X-Scope-OrgID: dev
        tls:
          insecure: true
      debug:
        verbosity: basic

    service:
      pipelines:
        traces:
          receivers:
            - otlp
          processors:
            - k8sattributes
          exporters:
            - otlp/tempo
            - debug

