apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: simplest
  namespace: rhcl-observability
  annotations:
    argocd.argoproj.io/sync-wave: "30"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  storage:
    secret:
      name: tempo-storage
      type: s3
  storageSize: 200M
  resources:
    total:
      limits:
        memory: 1Gi
        cpu: 1000m
  tenants:
    mode: static
    authentication:
      - tenantName: dev
        tenantId: "dev"
  template:
    gateway:
      enabled: true
      rbac:
        enabled: false
    queryFrontend:
      jaegerQuery:
        enabled: true

