apiVersion: v1
kind: Secret
metadata:
  name: mcp-gateway-config
  namespace: mcp-system
  labels:
    app: mcp-gateway
    mcp.kuadrant.io/aggregated: "true"
    mcp.kuadrant.io/secret: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "21"
type: Opaque
stringData:
  config.yaml: |
    servers:
      - enabled: true
        hostname: REPLACE_ME_MCP_HOSTNAME
        name: mcp-system/rhcl-mcp-tools
        toolPrefix: tools_
        url: https://REPLACE_ME_MCP_HOSTNAME/tools/rhcl-mcp-tools

