apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: rhcl-mcp-tools-internal-allow
  namespace: mcp-system
  annotations:
    argocd.argoproj.io/sync-wave: "33"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: rhcl-mcp-tools-internal
  defaults:
    rules:
      authorization:
        allow-all:
          opa:
            rego: "allow = true"

