apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: rhcl-mcp-gw-auth
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "23"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: rhcl-mcp-gw
  defaults:
    rules:
      authorization:
        deny-all:
          opa:
            rego: "allow = false"

