apiVersion: mcp.kuadrant.io/v1alpha1
kind: MCPServerRegistration
metadata:
  name: rhcl-mcp-tools
  namespace: mcp-system
  annotations:
    argocd.argoproj.io/sync-wave: "33"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  toolPrefix: tools_
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: rhcl-mcp-tools-internal
    namespace: mcp-system

