apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/namespace-observability.yaml
  - resources/namespace-tempo-operator.yaml
  - resources/namespace-opentelemetry-operator.yaml
  - resources/tempo-operator.yaml
  - resources/opentelemetry-operator.yaml
  - resources/odf-object-bucket.yaml
  - resources/tempostack.yaml
  - resources/networkpolicy-allow-mcp-to-tempo-distributor.yaml
  - resources/tempo-tenant-rbac.yaml
  - resources/otel-collector.yaml
  - resources/uiplugin-distributed-tracing.yaml

