apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/00-namespace-observability.yaml
  - resources/01-namespace-tempo-operator.yaml
  - resources/02-namespace-opentelemetry-operator.yaml
  - resources/03-namespace-cluster-observability-operator.yaml
  - resources/10-tempo-operator.yaml
  - resources/20-opentelemetry-operator.yaml
  - resources/30-cluster-observability-operator.yaml
  - resources/40-odf-object-bucket.yaml
  - resources/50-tempostack.yaml
  - resources/60-tempo-tenant-rbac.yaml
  - resources/70-otel-collector.yaml
  - resources/80-uiplugin-distributed-tracing.yaml

