apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/00-namespace.yaml
  - resources/00-namespace-keycloak.yaml
  - resources/00-namespace-oidc-portal.yaml
  - resources/05-console-banner.yaml
  - resources/10-demo-api.yaml
  - resources/15-ui.yaml
  - resources/15-oidc-ui.yaml
  - resources/16-ab-canary-external.yaml
  - resources/17-oidc-keycloak.yaml
  - resources/18-rhbk-operator.yaml
  - resources/20-gateway.yaml
  - resources/24-gateway-certificate.yaml
  - resources/25-gateway-tlspolicy.yaml
  - resources/26-gateway-dnspolicy.yaml
  - resources/30-httproute-api.yaml
  - resources/31-httproute-ui.yaml
  - resources/32-httproute-ab-canary-external.yaml
  - resources/33-httproute-keycloak.yaml
  - resources/33-httproute-oidc-portal.yaml
  - resources/34-httproute-ai-bot.yaml
  - resources/35-ai-bot.yaml
  - resources/36-httproute-jwt-demo.yaml
  - resources/38-oidc-referencegrant-external-proxy.yaml
  - resources/40-gateway-authpolicy.yaml
  - resources/50-api-keys.yaml
  - resources/60-route-authpolicy.yaml
  - resources/62-ui-authpolicy.yaml
  - resources/63-ab-authpolicy.yaml
  - resources/64-keycloak-authpolicy.yaml
  - resources/65-secure-jwt-authpolicy.yaml
  - resources/66-secure-oidcpolicy.yaml
  - resources/67-oidc-portal-authpolicy.yaml
  - resources/68-ai-bot-authpolicy.yaml
  - resources/69-jwt-demo-authpolicy.yaml
  - resources/70-route-ratelimitpolicy.yaml
  - resources/73-ai-bot-tokenratelimitpolicy.yaml
  - resources/80-route-passthrough.yaml
  - resources/81-route-oidc-passthrough.yaml
  - resources/90-istio-waypoint-demo.yaml
  - resources/91-istio-serviceentry-espn.yaml

configMapGenerator:
  - name: rhcl-ui
    namespace: demo
    files:
      - index.html=ui/index.html
  - name: rhcl-oidc-ui
    namespace: rhcl-oidc-portal
    files:
      - index.html=oidc-ui/index.html

generatorOptions:
  annotations:
    argocd.argoproj.io/sync-wave: "11"

