apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/namespaces
  - resources/apps
  - resources/gateway
  - resources/routes
  - resources/policies

configMapGenerator:
  - name: rhcl-ui
    namespace: demo
    files:
      - index.html=ui/index.html
  - name: rhcl-oidc-ui
    namespace: rhcl-oidc-portal
    files:
      - index.html=oidc-ui/index.html

generatorOptions:
  annotations:
    argocd.argoproj.io/sync-wave: "11"

