apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rhcl-gw-public-tls
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "21"
spec:
  secretName: rhcl-gw-public-tls
  dnsNames:
    - rhcl-workshop.REPLACE_ME_BASE_DOMAIN
    - oidc-rhcl-workshop.REPLACE_ME_BASE_DOMAIN
    - mcp.REPLACE_ME_BASE_DOMAIN
    - external.REPLACE_ME_BASE_DOMAIN
    - external-api.REPLACE_ME_BASE_DOMAIN
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: REPLACE_ME_CLUSTER_ISSUER

