apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    istio-discovery: enabled
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kiali-ossm
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: kiali-ossm
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "40"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  auth:
    strategy: anonymous
  deployment:
    accessible_namespaces:
      - '**'
    view_only_mode: false

