apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rhcl-gateway-metrics
  namespace: openshift-ingress
spec:
  namespaceSelector:
    matchNames:
      - openshift-ingress
  selector:
    matchLabels:
      app: rhcl-gateway-metrics
  endpoints:
    - port: envoy-prom
      path: /stats/prometheus
      scheme: http
      interval: 30s
      relabelings:
        - action: replace
          sourceLabels: [__meta_kubernetes_service_label_gateway]
          targetLabel: gateway
        - action: replace
          sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: gateway_namespace

