apiVersion: v1
kind: Service
metadata:
  name: rhcl-gw
  namespace: openshift-ingress
  labels:
    app: rhcl-gateway-metrics
    gateway: rhcl-gw
spec:
  selector:
    gateway.networking.k8s.io/gateway-name: rhcl-gw
  ports:
    - name: metrics
      port: 15020
      protocol: TCP
      targetPort: 15020
    - name: envoy-prom
      port: 15090
      protocol: TCP
      targetPort: 15090
---
apiVersion: v1
kind: Service
metadata:
  name: rhcl-mcp-gw
  namespace: openshift-ingress
  labels:
    app: rhcl-gateway-metrics
    gateway: rhcl-mcp-gw
spec:
  selector:
    gateway.networking.k8s.io/gateway-name: rhcl-mcp-gw
  ports:
    - name: metrics
      port: 15020
      protocol: TCP
      targetPort: 15020
    - name: envoy-prom
      port: 15090
      protocol: TCP
      targetPort: 15090

