apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rhcl-gateway-metrics
  namespace: openshift-ingress
spec:
  namespaceSelector:
    matchNames:
      - openshift-ingress
  selector:
    matchLabels:
      app: rhcl-gateway-metrics
  endpoints:
    - port: envoy-prom
      path: /stats/prometheus
      scheme: http
      interval: 30s

