apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: rhcl-tempo
  namespace: monitoring
  labels:
    app: rhcl-grafana
  annotations:
    argocd.argoproj.io/sync-wave: "97"
spec:
  instanceSelector:
    matchLabels:
      app: rhcl-grafana
  valuesFrom:
    - targetPath: "secureJsonData.httpHeaderValue1"
      valueFrom:
        secretKeyRef:
          name: rhcl-grafana-tempo
          key: TEMPO_TOKEN
  datasource:
    name: rhcl-tracing
    type: jaeger
    access: proxy
    isDefault: false
    url: https://tempo-simplest-gateway.rhcl-observability.svc.cluster.local:8080/api/traces/v1/dev
    jsonData:
      tlsSkipVerify: true
      httpHeaderName1: "Authorization"
    secureJsonData:
      httpHeaderValue1: "Bearer ${TEMPO_TOKEN}"

