apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-demo.yaml
  - namespace-demo-ab.yaml
  - namespace-demo-jwt.yaml
  - namespace-rhcl-ai-bot.yaml
  - namespace-rhcl-keycloak.yaml
  - namespace-rhcl-oidc-portal.yaml

