apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/resources/namespaces/namespace-rhcl-keycloak.yaml
  - ../../base/resources/apps/rhbk-operator.yaml
  - ../../base/resources/apps/keycloak.yaml
  - ../../base/resources/routes/httproute-keycloak.yaml
  - ../../base/resources/policies/keycloak-authpolicy.yaml

