apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/namespace-mcp-system.yaml
  - resources/mcp-gateway-olm.yaml
  - resources/mcp-gateway-config-secret.yaml
  - resources/mcp-gateway-authpolicy.yaml
  - resources/mcp-authpolicy.yaml
  - resources/mcp-tools-authpolicy.yaml
  - resources/mcp-gateway-gateway.yaml
  - resources/mcp-gateway-public-dnspolicy.yaml
  - resources/mcp-gateway-referencegrant.yaml
  - resources/mcp-gateway-extension.yaml
  - resources/mcp-gateway-public-httproute.yaml
  - resources/rhcl-mcp-tools.yaml
  - resources/httproute-rhcl-mcp-tools.yaml
  - resources/rhcl-mcp-tools-bridge.yaml
  - resources/referencegrant-demo-to-mcp-tools-bridge.yaml
  - resources/mcp-otel-collector.yaml
  - resources/mcp-gateway-otel-rbac.yaml
  - resources/mcp-gateway-otel-env-job.yaml

