apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/00-namespace-mcp-system.yaml
  - resources/10-kuadrant-mcp-server.yaml
  - resources/20-httproute-mcp.yaml
  - resources/30-mcp-authpolicy.yaml

