apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/resources/namespaces/namespace-rhcl-oidc-portal.yaml
  - ../../base/resources/istio/istio-waypoint-rhcl-oidc-portal.yaml
  - ../../base/resources/apps/oidc-ui.yaml
  - ../../base/resources/apps/oidc-callback.yaml
  - ../../base/resources/routes/httproute-oidc-portal.yaml
  - ../../base/resources/routes/referencegrant-oidc-to-external-proxy.yaml
  - ../../base/resources/policies/secure-jwt-authpolicy.yaml
  - ../../base/resources/policies/secure-oidcpolicy.yaml
  - ../../base/resources/policies/oidc-portal-authpolicy.yaml

configMapGenerator:
  - name: rhcl-oidc-ui
    namespace: rhcl-oidc-portal
    files:
      - index.html=../../base/oidc-ui/index.html
  - name: oidc-callback
    namespace: rhcl-oidc-portal
    files:
      - server.js=../../base/oidc-callback/server.js

generatorOptions:
  annotations:
    argocd.argoproj.io/sync-wave: "11"

