apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway-authpolicy.yaml
  - api-keys.yaml
  - route-authpolicy.yaml
  - ui-authpolicy.yaml
  - ab-authpolicy.yaml
  - keycloak-authpolicy.yaml
  - jwt-demo-authpolicy.yaml
  - external-proxy-authpolicy.yaml
  - secure-jwt-authpolicy.yaml
  - secure-oidcpolicy.yaml
  - oidc-portal-authpolicy.yaml
  - ai-bot-main-authpolicy.yaml
  - ai-bot-main-tokenratelimitpolicy.yaml
  - ai-bot-ai-tokenratelimitpolicy.yaml
  - route-ratelimitpolicy.yaml

