apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../resources/minio-tempo-storage.yaml
  - ../resources/otel-collector.yaml
  - ../resources/uiplugin-distributed-tracing.yaml
  - ../resources/distributed-tracing-auth-proxy.yaml
  - ../resources/patch-consoleplugin-distributed-tracing-proxy.yaml

