apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: rhcl-gw-mcp
  namespace: openshift-ingress
spec:
  host: mcp.apps.cluster-rjzd5.rjzd5.sandbox921.opentlc.com
  to:
    kind: Service
    name: rhcl-gw-istio
  port:
    targetPort: 443
  tls:
    termination: passthrough
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rhcl-mcp
  namespace: rhcl-ai-bot
spec:
  hostnames:
    - mcp.apps.cluster-rjzd5.rjzd5.sandbox921.opentlc.com
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: rhcl-gw
      namespace: openshift-ingress
      sectionName: https-mcp-public
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /mcp
      backendRefs:
        - kind: Service
          name: rhcl-ai-bot
          port: 80
---
apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: rhcl-mcp-allow
  namespace: rhcl-ai-bot
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: rhcl-mcp
  defaults:
    rules:
      authorization:
        allow-all:
          opa:
            rego: |
              allow = true
---
apiVersion: kuadrant.io/v1
kind: DNSPolicy
metadata:
  name: rhcl-oidc-sandbox-dns
  namespace: openshift-ingress
spec:
  providerRefs:
    - name: route53-credentials
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: rhcl-gw
    sectionName: https-oidc-sandbox
---
apiVersion: kuadrant.io/v1
kind: DNSPolicy
metadata:
  name: rhcl-ai-sandbox-dns
  namespace: openshift-ingress
spec:
  providerRefs:
    - name: route53-credentials
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: rhcl-ai-gw
    sectionName: https-ai-sandbox
