apiVersion: v1
kind: Secret
metadata:
  name: rhcl-tracing-s3-creds
  namespace: openshift-cluster-observability-operator
type: Opaque
stringData:
  access_key_secret: tempo-tempo-tempo
---
apiVersion: observability.openshift.io/v1alpha1
kind: ObservabilityInstaller
metadata:
  name: rhcl-tracing
  namespace: openshift-cluster-observability-operator
spec:
  capabilities:
    tracing:
      enabled: true
      operators:
        install: false
      storage:
        objectStorage:
          s3:
            endpoint: http://tempo-minio.rhcl-observability.svc.cluster.local:9000
            bucket: tempo-traces
            accessKeyID: tempo
            accessKeySecret:
              name: rhcl-tracing-s3-creds
              key: access_key_secret

