apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/resources/namespaces/namespace-demo.yaml
  - ../../base/resources/namespaces/namespace-demo-ab.yaml
  - ../../base/resources/namespaces/namespace-demo-jwt.yaml
  - ../../base/resources/apps/demo-api.yaml
  - ../../base/resources/apps/ui.yaml
  - ../../base/resources/apps/ab-canary.yaml
  - ../../base/resources/apps/external-proxy.yaml
  - ../../base/resources/routes/httproute-api.yaml
  - ../../base/resources/routes/httproute-ui.yaml
  - ../../base/resources/routes/httproute-ab-canary-external.yaml
  - ../../base/resources/routes/httproute-jwt-demo.yaml
  - ../../base/resources/routes/httproute-mcp-tools-local.yaml
  - ../../base/resources/routes/httproute-external-proxy.yaml
  - ../../base/resources/routes/httproute-external-proxy-public.yaml
  - ../../base/resources/routes/referencegrant-jwt-to-external-proxy.yaml
  - ../../base/resources/policies/api-keys.yaml
  - ../../base/resources/policies/route-authpolicy.yaml
  - ../../base/resources/policies/ui-authpolicy.yaml
  - ../../base/resources/policies/ab-authpolicy.yaml
  - ../../base/resources/policies/mcp-tools-local-authpolicy.yaml
  - ../../base/resources/policies/jwt-demo-authpolicy.yaml
  - ../../base/resources/policies/route-ratelimitpolicy.yaml
  - ../../base/resources/policies/external-proxy-authpolicy.yaml

configMapGenerator:
  - name: rhcl-ui
    namespace: demo
    files:
      - index.html=../../base/ui/index.html

generatorOptions:
  annotations:
    argocd.argoproj.io/sync-wave: "11"
  disableNameSuffixHash: true

