apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/namespace.yaml
  - resources/openapi-demo-api.yaml
  - resources/api-keys.yaml
  - resources/generated/httproute.yaml
  - resources/generated/authpolicy.yaml
  - resources/generated/ratelimitpolicy.yaml

