apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/resources/namespaces/namespace-rhcl-ai-bot.yaml
  - ../../base/resources/routes/httproute-ai-bot-main.yaml
  - ../../base/resources/apps/ai-bot.yaml
  - ../../base/resources/policies/ai-bot-main-authpolicy.yaml
  - ../../base/resources/policies/ai-bot-main-tokenratelimitpolicy.yaml

