apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: rhcl-gw
  namespace: openshift-ingress
  labels:
    kuadrant.io/gateway: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  gatewayClassName: openshift-default
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: https-main
      port: 443
      protocol: HTTPS
      hostname: rhcl-workshop.apps.cluster-lmc6n.lmc6n.sandbox1529.opentlc.com
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: rhcl-gw-tls
      allowedRoutes:
        namespaces:
          from: All
    - name: https-oidc
      port: 443
      protocol: HTTPS
      hostname: oidc-rhcl-workshop.apps.cluster-lmc6n.lmc6n.sandbox1529.opentlc.com
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: rhcl-gw-tls
      allowedRoutes:
        namespaces:
          from: All

