apiVersion: kuadrant.io/v1
kind: DNSPolicy
metadata:
  name: rhcl-ai-dns
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "22"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: rhcl-ai-gw
    sectionName: https-ai
  providerRefs:
    - name: route53-credentials

