apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: demo-api
  namespace: demo
  labels:
    app: demo-api
    service: demo-api
    deployment: demo-api
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  hostnames:
    - rhcl-workshop.apps.cluster-lmc6n.lmc6n.sandbox1529.opentlc.com
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: rhcl-gw
      namespace: openshift-ingress
  rules:
    - matches:
        - method: GET
          path:
            type: PathPrefix
            value: /hello
        - method: GET
          path:
            type: PathPrefix
            value: /health
      backendRefs:
        - group: ""
          kind: Service
          name: demo-api
          port: 80
          weight: 1

