apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ai-bot
  namespace: demo
  labels:
    app: rhcl-ai-bot
    service: rhcl-ai-bot
    deployment: rhcl-ai-bot
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: rhcl-gw
      namespace: openshift-ingress
  rules:
    - matches:
        - method: GET
          path:
            type: PathPrefix
            value: /mcp
        - method: POST
          path:
            type: PathPrefix
            value: /mcp
        - method: POST
          path:
            type: PathPrefix
            value: /ai
      backendRefs:
        - group: ""
          kind: Service
          name: rhcl-ai-bot
          port: 80
          weight: 1

