apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: secure-demo-jwt
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "32"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: secure-demo
  defaults:
    rules:
      authentication:
        jwt:
          jwt:
            issuerUrl: https://REPLACE_ME_DEMO_HOSTNAME/auth/realms/rhcl
          credentials:
            authorizationHeader:
              prefix: "Bearer"
      authorization:
        allow-all:
          opa:
            rego: "allow = true"

