apiVersion: extensions.kuadrant.io/v1alpha1
kind: OIDCPolicy
metadata:
  name: secure-demo-oidc
  namespace: rhcl-oidc-portal
  annotations:
    argocd.argoproj.io/sync-wave: "32"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: secure-demo
  provider:
    clientID: rhcl-ui
    issuerURL: https://oidc-rhcl-workshop.apps.cluster-lmc6n.lmc6n.sandbox1529.opentlc.com/auth/realms/rhcl
    authorizationEndpoint: https://oidc-rhcl-workshop.apps.cluster-lmc6n.lmc6n.sandbox1529.opentlc.com/auth/realms/rhcl/protocol/openid-connect/auth
    tokenEndpoint: https://oidc-rhcl-workshop.apps.cluster-lmc6n.lmc6n.sandbox1529.opentlc.com/auth/realms/rhcl/protocol/openid-connect/token
    redirectURI: https://oidc-rhcl-workshop.apps.cluster-lmc6n.lmc6n.sandbox1529.opentlc.com/oidc/callback
  auth:
    tokenSource:
      cookie:
        name: rhcl_token

