apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: ai-bot-main-allow
  namespace: rhcl-ai-bot
  annotations:
    argocd.argoproj.io/sync-wave: "32"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: ai-bot-main
  defaults:
    rules:
      authorization:
        allow-all:
          opa:
            rego: "allow = true"

