apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhcl-workshop
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/panchoraposo/demo-rhcl.git
    targetRevision: main
    path: gitops/argocd
    kustomize:
      buildOptions: "--load-restrictor LoadRestrictionsNone"
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

