apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/namespace-gateway-system.yaml
  - resources/namespace-monitoring.yaml
  - ../../base/resources/apps/console-banner.yaml
  - ../../base/resources/gateway/gateway.yaml
  - ../../base/resources/routes/httproute-http-to-https.yaml
  - ../../base/resources/gateway/gateway-public-certificate.yaml
  - ../../base/resources/gateway/gateway-dnspolicy.yaml
  - ../../base/resources/gateway/gateway-public-dnspolicy-main.yaml
  - ../../base/resources/policies/gateway-authpolicy.yaml
  - resources/workshop-users-rbac.yaml
  - resources/enable-kuadrant-console-plugin.yaml
  - resources/enable-user-workload-monitoring.yaml
  - resources/install-kuadrant-observability-config.yaml
  - resources/grafana-rbac.yaml
  - resources/grafana-thanos-token.yaml
  - resources/grafana-tempo-sa.yaml
  - resources/grafana-tempo-token.yaml
  - resources/grafana.yaml
  - resources/grafana-datasource-thanos.yaml
  - resources/grafana-datasource-tempo.yaml
  - resources/grafana-dashboard-configmaps.yaml
  - resources/grafana-dashboards.yaml
  - resources/gateway-metrics-services.yaml
  - resources/gateway-metrics-servicemonitor.yaml
  - resources/gatewayapi-state-metrics.yaml
  - resources/rhcl-gateway-trafficanalysis-prometheusrule.yaml

